apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: custom-redhat-operators
  namespace: openshift-marketplace
spec:
  displayName: Red Hat Operators
  image: dhcp16-231-198.ptp.lab.eng.bos.redhat.com:5000/custom-redhat-operators:1.0.0
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m0s