#!/bin/bash
set -e
. /usr/local/bin/common

# Pull the image into the cache directory and attain the image ID
IMAGE_ID=$(podman pull --quiet  $REDHAT_OPERATORS_INDEX --root="/cache" --authfile=/var/lib/kubelet/config.json )
echo "$REDHAT_OPERATORS_INDEX image ID is $IMAGE_ID"

# Mount the image, so image-references can be used
IMAGE_MOUNT=$(podman --root="/cache" image mount $IMAGE_ID)
echo "Image mount: $IMAGE_MOUNT"

# Extract the database
cp $IMAGE_MOUNT/database/index.db /tmp/
echo "Extracted index database"

/usr/libexec/platform-python /usr/local/bin/olm.py >> /tmp/images.txt
echo "OLM processing done, Image list:\n$(cat /tmp/images.txt)"
