#!/bin/bash
set -e
. /usr/local/bin/common

process_index_db(){
    db_path=$1
    operators_spec_file=$2

    log_debug "Index image is database-based. This format is deprecated."
    /usr/bin/python3 /usr/local/bin/olm_db.py "${db_path}" "${operators_spec_file}" "/tmp/images.txt"
    return $?
}

process_index_filesystem(){
    index_path=$1
    log_debug "Index image is file system based. This format is not yet implemented."
    return 1

}

main(){
    declare -i ret_val=0
    # There could be several indexes, hence the loop
    for index in $(sort -u /etc/config/operators.indexes) ; do
        image_id=$(buildah pull --quiet  --root="/cache" --authfile=/var/lib/kubelet/config.json $index)
        log_debug "$index image ID is $image_id"
        image_mount=$(buildah --root="/cache" image mount $image_id)
        log_debug "Image mount: $image_mount"
        operators_spec_file="/etc/config/operators.packagesAndChannels"
        if [[ -f "$image_mount/database/index.db" ]]; then
            process_index_db $image_mount/database/index.db $operators_spec_file
        else
            process_index_filesystem $image_mount $operators_spec
        fi
        ret_val=ret_val+$?
        buildah image unmount $image_id
    done
    log_debug "OLM pull spec extraction done"
    if [[ $ret_val -ne 0 ]]; then
        log_debug "Some of the extractions failed, please check the log."
    fi
    return $ret_val
}

if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
  main "${@}"
  exit $?
fi
