apiVersion: v1
kind: Namespace
metadata:
  name: pre-cache
  annotations:
    workload.openshift.io/allowed: management
---
apiVersion: v1
kind: Pod
metadata:
  name: pre-cache
  namespace: pre-cache
spec:
  containers:
  - name: pre-cache-container
    image: quay.io/vgrinber/pre-cache:latest
    env:
    - name: pull_timeout_sec
      value: "600"
    command:
    - /bin/bash
    - -c
    args:
    - sleep inf
    # - /usr/local/bin/release && /usr/local/bin/olm && /usr/local/bin/pull
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - mountPath: /cache
      name: cache
    - mountPath: /var/lib/containers
      name: varlibcontainers
    - mountPath: /var/lib/kubelet
      name: varlibkubelet
    - mountPath: /etc/config 
      name: config-volume
  volumes:
  - name: cache
    emptyDir: {}
  - name: varlibcontainers
    hostPath:
      path: /var/lib/containers
  - name: varlibkubelet
    hostPath:
      path: /var/lib/kubelet
  - name: config-volume
    configMap:
      name: pre-cache-spec
  restartPolicy: Never