#!/bin/bash

# Point to the internal API server hostname
APISERVER=https://kubernetes.default.svc

# Path to ServiceAccount token
SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount

# Read this Pod's namespace
NAMESPACE=$(cat ${SERVICEACCOUNT}/namespace)

# Read the ServiceAccount bearer token
TOKEN=$(cat ${SERVICEACCOUNT}/token)

# Reference the internal certificate authority (CA)
CACERT=${SERVICEACCOUNT}/ca.crt

# Pull the image into the cache directory and attain the image ID
IMAGE_ID=$(podman pull --quiet  $REL_IMG --root="/cache")

# Mount the image, so image-references can be used
IMAGE_MOUNT=$(podman --root="/cache" image mount $IMAGE_ID)

# Store the extracted image specification in an ImageStream object
curl --data @${IMAGE_MOUNT}/release-manifests/image-references \
    --cacert ${CACERT} \
    --header "Authorization: Bearer ${TOKEN}" \
    --header "Content-Type: application/json" \
    --request POST ${APISERVER}/apis/image.openshift.io/v1/namespaces/${NAMESPACE}/imagestreams