#!/bin/bash
set -e
. /opt/precache/common

REL_IMG=$(cat $config_volume_path/platform.image)

# Pull the image into the cache directory and attain the image ID
IMAGE_ID=$(podman pull --quiet  $REL_IMG --root="/cache")
log_debug "$REL_IMG image ID is $IMAGE_ID"

# Mount the image, so image-references can be used
IMAGE_MOUNT=$(podman --root="/cache" image mount $IMAGE_ID)
log_debug "Image mount: $IMAGE_MOUNT"

cat ${IMAGE_MOUNT}/release-manifests/image-references |jq '.spec.tags[].from.name' >> /tmp/images.txt
log_debug "RELEASE processing done, Image list:"
log_debug $(cat /tmp/images.txt)
