#!/bin/bash
set -e
. /usr/local/bin/common

if [[ ! -f "/etc/config/platform.image" ]]; then
    debug_log "Platform image definition not found. Does pre-cache-spec configmap exist?"
    exit 1
fi

$REL_IMG=$(cat /etc/config/platform.image)

# Pull the image into the cache directory and attain the image ID
IMAGE_ID=$(podman pull --quiet  $REL_IMG --root="/cache")
echo "$REL_IMG image ID is $IMAGE_ID"

# Mount the image, so image-references can be used
IMAGE_MOUNT=$(podman --root="/cache" image mount $IMAGE_ID)
echo "Image mount: $IMAGE_MOUNT"

cat ${IMAGE_MOUNT}/release-manifests/image-references |jq '.spec.tags[].from.name' >> /tmp/images.txt
echo "RELEASE processing done, Image list:"
echo $(cat /tmp/images.txt)
