kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pre-cache-role
rules:
- apiGroups:
  - image.openshift.io
  resources:
  - imagestreams
  verbs:
  - get
  - watch
  - list
  - create
  - delete
  - patch
  - update