apiVersion: v1
kind: Namespace
metadata:
  name: pre-cache
  annotations:
    workload.openshift.io/allowed: management
---
apiVersion: v1
kind: Pod
metadata:
  name: pre-cache
  namespace: pre-cache
spec:
  containers:
  - name: pre-cache-container
    image: quay.io/vgrinber/pre-cache:latest
    env:
    - name: REL_IMG
      value: quay.io/openshift-release-dev/ocp-release:4.9.0-x86_64
    - name: REDHAT_OPERATORS
      value: advanced-cluster-management,local-storage-operator,ocs-operator,performance-addon-operator,ptp-operator,sriov-network-operator
    - name: COMMUNITY_OPERATORS
      value: hive-operator
    - name: OCP_RELEASE
      value: "4.9"
    command:
    # - /bin/bash
    # - -c
    # - "sleep inf"
    - /bin/bash
    - -c
    args:
    - /usr/local/bin/release; sleep inf
    securityContext:
      privileged: true
      runAsUser: 0
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
    - mountPath: /var/lib
      name: varlib
  volumes:
  - name: cache-volume
    emptyDir: {}
  - name: varlib
    hostPath:
      path: /var/lib
  restartPolicy: Never