apiVersion: batch/v1
kind: Job
metadata:
  name: pre-cache
spec:
  backoffLimit: 0
  activeDeadlineSeconds: 14400
  template:
    metadata:
      name: pre-cache
    spec:
      containers:
      - name: pre-cache-container
        image: quay.io/vgrinber/pre-cache:latest
        env:
        - name: pull_timeout
          value: "600"
        - name: config_volume_path
          value: /etc/config
        command:
        - /bin/bash
        - -c
        args:
        - sleep inf
        #- /usr/local/bin/release && /usr/local/bin/olm && /usr/local/bin/pull
        securityContext:
          privileged: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /cache
          name: cache
        - mountPath: /var/lib/containers
          name: varlibcontainers
        - mountPath: /var/lib/kubelet/config.json
          name: pull
        - mountPath: /etc/config 
          name: config-volume
        - mountPath: /etc/containers/registries.conf
          name: registries
        - mountPath: /etc/docker
          name: etcdocker
      nodeSelector:
        node-role.kubernetes.io/master: ''
      serviceAccount: pre-cache-agent
      serviceAccountName: pre-cache-agent
      volumes:
      - name: cache
        emptyDir: {}
      - name: varlibcontainers
        hostPath:
          path: /var/lib/containers
      - name: registries
        hostPath:
          path: /etc/containers/registries.conf
      - name: etcdocker
        hostPath:
          path: /etc/docker
      - name: pull
        hostPath:
          path: /var/lib/kubelet/config.json
      - name: config-volume
        configMap:
          name: pre-cache-spec
      restartPolicy: Never                  